### ISSUE TITLE
Datatable not translated

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/localisation#33]
Do you have an idea why my datatable is not translated (not in default tables too, e.g. users)

<img width="1122" alt="screenshot 2018-03-24 14 56 53" src="https://user-images.githubusercontent.com/7204559/37864805-b5c9289e-2f73-11e8-8571-8d717991b7c0.png">

**Comment by aocneanu** [comment]
Because yours are yours and I programmed it to only translate mine :P

This happens because starting with an update (check the changelog) `VueTable`, `VueForm`, `VueSelect` and `Notifications` are able to autodetect if in the project exists a prototype method "__" and if so, use it. (so don't pass it anymore)

In all the pages in Enso, you should use this `__` global helper instead of the `mapGetters('locale', ['__'])` for translation. So refactor everything and drop the `mapGetters...`This is because we needed `addKey` to do more than to be a getter.

**Comment by mauthi** [comment]
Found the error, my vuedatatable was on 1.0.89 - therefore I didn't get the last update.
But I don't know how I installed 1.0.89
